# Generated by Django 5.2.9 on 2026-01-18 18:34

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0005_applicationconfiguration_ai_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationconfiguration",
            name="docling_endpoint",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Docling endpoint",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="docling_force_ocr",
            field=models.BooleanField(null=True, verbose_name="Docling force OCR"),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="docling_language",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                verbose_name="Docling language",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="docling_timeout",
            field=models.PositiveIntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Docling timeout",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="ocr_alignment_threshold",
            field=models.FloatField(
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="OCR alignment threshold",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="ocr_custom_alignment",
            field=models.BooleanField(null=True, verbose_name="OCR custom alignment"),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="ocr_engine",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tesseract", "Tesseract"),
                    ("docling", "Docling"),
                    ("ollama", "Ollama"),
                ],
                default="tesseract",
                max_length=16,
                null=True,
                verbose_name="Sets the OCR engine",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="ocr_sharpen",
            field=models.BooleanField(null=True, verbose_name="OCR sharpen"),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="ocr_sharpen_percent",
            field=models.FloatField(
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="OCR sharpen percent",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="ocr_sharpen_radius",
            field=models.FloatField(
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="OCR sharpen radius",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="ocr_sharpen_threshold",
            field=models.FloatField(
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="OCR sharpen threshold",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="ollama_endpoint",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Ollama endpoint",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="ollama_model",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Ollama model",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="ollama_prompt_template",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Ollama prompt template",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="ollama_timeout",
            field=models.PositiveIntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Ollama timeout",
            ),
        ),
    ]
