# Generated by Django 5.2.11 on 2026-02-05 17:39

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0006_applicationconfiguration_barcode_tag_split"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationconfiguration",
            name="ocr_engine_priority",
            field=models.CharField(
                blank=True,
                help_text="Ordered list of OCR engines to try, comma-separated. First engine in the list has the highest priority. Example: 'docling,tesseract,ollama'",
                max_length=256,
                null=True,
                verbose_name="OCR engine priority",
            ),
        ),
    ]
