# Generated by Django 5.2.9 on 2026-01-24 12:06

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0006_applicationconfiguration_docling_endpoint_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationconfiguration",
            name="ocr_engine",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tesseract", "Tesseract"),
                    ("docling", "Docling (Local)"),
                    ("docling_server", "Docling Server"),
                    ("ollama", "Ollama"),
                ],
                default="tesseract",
                max_length=16,
                null=True,
                verbose_name="Sets the OCR engine",
            ),
        ),
    ]
