# Generated by Django 5.2.11 on 2026-02-08 00:22

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0006_applicationconfiguration_barcode_tag_split"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationconfiguration",
            name="ai_system_prompt",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="AI system prompt",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="llm_embedding_api_key",
            field=models.CharField(
                blank=True,
                max_length=1024,
                null=True,
                verbose_name="Sets the LLM embedding API key, optional",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="llm_embedding_endpoint",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Sets the LLM embedding endpoint, optional",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="llm_timeout",
            field=models.PositiveIntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="LLM request timeout (seconds)",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="vector_store_backend",
            field=models.CharField(
                blank=True,
                choices=[
                    ("auto", "Automatic (suggested)"),
                    ("faiss", "FAISS (local files)"),
                    ("postgres", "Postgres (PGVector)"),
                ],
                default="auto",
                max_length=16,
                null=True,
                verbose_name="Vector store backend",
            ),
        ),
        migrations.AlterField(
            model_name="applicationconfiguration",
            name="llm_embedding_backend",
            field=models.CharField(
                blank=True,
                choices=[
                    ("openai", "OpenAI"),
                    ("huggingface", "Huggingface"),
                    ("ollama", "Ollama"),
                ],
                max_length=128,
                null=True,
                verbose_name="Sets the LLM embedding backend",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="vector_store_host",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Vector store host",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="vector_store_port",
            field=models.PositiveIntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Vector store port",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="vector_store_user",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Vector store user",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="vector_store_password",
            field=models.CharField(
                blank=True,
                max_length=1024,
                null=True,
                verbose_name="Vector store password",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="vector_store_database",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Vector store database",
            ),
        ),
    ]
