# Generated by Django 5.2.11 on 2026-02-05 22:48

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0007_applicationconfiguration_ocr_engine_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationconfiguration",
            name="docling_endpoint",
            field=models.CharField(
                blank=True,
                help_text="Base URL for Docling server API (e.g., http://localhost:5001). Leave blank to use local Docling library if installed.",
                max_length=256,
                null=True,
                verbose_name="Docling endpoint",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="docling_force_ocr",
            field=models.BooleanField(
                help_text="Force OCR even if the PDF already contains text. Useful for improving quality of born-digital PDFs.",
                null=True,
                verbose_name="Docling force OCR",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="docling_language",
            field=models.CharField(
                blank=True,
                help_text="Language code for OCR (e.g., 'eng', 'deu'). Defaults to OCR_LANGUAGE.",
                max_length=32,
                null=True,
                verbose_name="Docling language",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="docling_timeout",
            field=models.PositiveIntegerField(
                help_text="Timeout in seconds for Docling processing. Default: 120.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Docling timeout",
            ),
        ),
    ]
