# Generated by Django 5.2.9 on 2026-01-24 14:14

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0007_alter_applicationconfiguration_ocr_engine"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationconfiguration",
            name="llm_timeout",
            field=models.PositiveIntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="LLM request timeout (seconds)",
            ),
        ),
    ]
