# Generated by Django 5.2.9 on 2026-01-24 16:33

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0008_add_llm_timeout"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationconfiguration",
            name="ollama_ocr_debug_thumbnail",
            field=models.BooleanField(
                null=True,
                verbose_name="Ollama OCR debug thumbnail",
            ),
        ),
    ]
