# Generated by Django 5.2.9 on 2026-01-24 23:04

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0009_applicationconfiguration_ollama_ocr_debug_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationconfiguration",
            name="llm_embedding_api_key",
            field=models.CharField(
                blank=True,
                max_length=1024,
                null=True,
                verbose_name="Sets the LLM embedding API key, optional",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="llm_embedding_endpoint",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Sets the LLM embedding endpoint, optional",
            ),
        ),
        migrations.AlterField(
            model_name="applicationconfiguration",
            name="llm_embedding_backend",
            field=models.CharField(
                blank=True,
                choices=[
                    ("openai", "OpenAI"),
                    ("huggingface", "Huggingface"),
                    ("ollama", "Ollama"),
                ],
                max_length=128,
                null=True,
                verbose_name="Sets the LLM embedding backend",
            ),
        ),
    ]
