# Generated by Django 5.2.9 on 2026-01-24 23:38

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0010_applicationconfiguration_llm_embedding_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationconfiguration",
            name="vector_store_backend",
            field=models.CharField(
                blank=True,
                choices=[
                    ("auto", "Automatic (suggested)"),
                    ("faiss", "FAISS (local files)"),
                    ("postgres", "Postgres (PGVector)"),
                ],
                default="auto",
                max_length=16,
                null=True,
                verbose_name="Vector store backend",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="vector_store_host",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Vector database host",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="vector_store_name",
            field=models.CharField(
                blank=True,
                help_text="Defaults to <main-db-name>-vector",
                max_length=256,
                null=True,
                verbose_name="Vector database name",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="vector_store_pass",
            field=models.CharField(
                blank=True,
                max_length=1024,
                null=True,
                verbose_name="Vector database password",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="vector_store_port",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Vector database port",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="vector_store_user",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Vector database user",
            ),
        ),
    ]
