# Generated by Django 5.2.10 on 2026-01-25 18:53

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0011_applicationconfiguration_vector_store_backend_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationconfiguration",
            name="ai_system_prompt",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="AI system prompt",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="auto_create_threshold",
            field=models.FloatField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
                verbose_name="Auto create threshold",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="confidence_threshold",
            field=models.FloatField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
                verbose_name="Confidence threshold",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="enable_auto_ai_enhancement",
            field=models.BooleanField(
                null=True,
                verbose_name="Enable Auto AI Enhancement",
            ),
        ),
    ]
