# Generated by Django 5.2.10 on 2026-02-04 22:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0006_applicationconfiguration_barcode_tag_split"),
        ("paperless", "0012_applicationconfiguration_ai_system_prompt_and_more"),
    ]

    operations = []
