# Generated by Django 5.2.11 on 2026-02-08 10:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0007_applicationconfiguration_ai_system_prompt_and_more"),
        ("paperless", "0013_merge_20260204_2214"),
    ]

    operations = []
