# Generated by Django 5.2.11 on 2026-02-08 19:00

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0013_merge_20260204_2214"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationconfiguration",
            name="barcode_tag_split",
            field=models.BooleanField(
                default=False,
                help_text="Split barcode values into separate tags using configured separator",
                verbose_name="barcode tag split",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="vector_store_database",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="vector store database",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="vector_store_password",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="vector store password",
            ),
        ),
        migrations.AlterField(
            model_name="applicationconfiguration",
            name="vector_store_host",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="vector store host",
            ),
        ),
        migrations.AlterField(
            model_name="applicationconfiguration",
            name="vector_store_port",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="vector store port",
            ),
        ),
        migrations.AlterField(
            model_name="applicationconfiguration",
            name="vector_store_user",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="vector store user",
            ),
        ),
    ]
