# Generated by Django 5.2.11 on 2026-02-08 10:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0014_merge_20260208_1053"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicationconfiguration",
            name="vector_store_name",
        ),
        migrations.RemoveField(
            model_name="applicationconfiguration",
            name="vector_store_pass",
        ),
    ]
