# Generated by Django 5.2.11 on 2026-02-08 10:59

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        (
            "paperless",
            "0015_remove_applicationconfiguration_vector_store_name_and_more",
        ),
        ("paperless", "0007_applicationconfiguration_ai_system_prompt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationconfiguration",
            name="audit_log_level",
            field=models.CharField(
                blank=True,
                default="INFO",
                max_length=16,
                null=True,
                verbose_name="Audit log level",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="force_ai_update",
            field=models.BooleanField(
                default=False,
                null=True,
                verbose_name="Force AI update",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="graceful_degradation",
            field=models.BooleanField(
                default=True,
                null=True,
                verbose_name="Graceful degradation",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="rate_limit_requests",
            field=models.PositiveIntegerField(
                default=100,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Rate limit requests",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="rate_limit_window",
            field=models.PositiveIntegerField(
                default=60,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Rate limit window",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="rollback_enabled",
            field=models.BooleanField(
                default=True,
                null=True,
                verbose_name="Enable rollback",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="rollback_retention_days",
            field=models.PositiveIntegerField(
                default=30,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Rollback retention days",
            ),
        ),
    ]
