# Generated by Django 5.2.11 on 2026-02-09 12:00

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0016_applicationconfiguration_audit_log_level_and_more"),
    ]

    operations = [
        # Remove Ollama OCR fields
        migrations.RemoveField(
            model_name="applicationconfiguration",
            name="ollama_endpoint",
        ),
        migrations.RemoveField(
            model_name="applicationconfiguration",
            name="ollama_model",
        ),
        migrations.RemoveField(
            model_name="applicationconfiguration",
            name="ollama_prompt_template",
        ),
        migrations.RemoveField(
            model_name="applicationconfiguration",
            name="ollama_timeout",
        ),
        migrations.RemoveField(
            model_name="applicationconfiguration",
            name="ollama_ocr_debug_thumbnail",
        ),
        # Add OCR engine priority field
        migrations.AddField(
            model_name="applicationconfiguration",
            name="ocr_engine_priority",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated list of OCR engines in priority order (e.g., 'tesseract,docling,docling_server')",
                null=True,
                verbose_name="OCR engine priority",
            ),
        ),
        # Update OCR engine choices to remove 'ollama'
        migrations.AlterField(
            model_name="applicationconfiguration",
            name="ocr_engine",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tesseract", "Tesseract"),
                    ("docling", "Docling (Local)"),
                    ("docling_server", "Docling Server"),
                ],
                default="tesseract",
                max_length=16,
                null=True,
                verbose_name="Sets the OCR engine",
            ),
        ),
    ]
