# Generated by Django 5.2.11 on 2026-03-09 21:14

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0017_remove_ollama_ocr_fields_and_add_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationconfiguration",
            name="barcode_tag_split",
            field=models.BooleanField(
                default=False,
                verbose_name="Enables splitting on tag barcodes",
            ),
        ),
        migrations.AlterField(
            model_name="applicationconfiguration",
            name="llm_backend",
            field=models.CharField(
                blank=True,
                choices=[("openai", "OpenAI-Compatible"), ("ollama", "Ollama")],
                max_length=128,
                null=True,
                verbose_name="Sets the LLM backend",
            ),
        ),
        migrations.AlterField(
            model_name="applicationconfiguration",
            name="llm_embedding_backend",
            field=models.CharField(
                blank=True,
                choices=[
                    ("openai", "OpenAI-Compatible"),
                    ("huggingface", "Huggingface"),
                    ("ollama", "Ollama"),
                ],
                max_length=128,
                null=True,
                verbose_name="Sets the LLM embedding backend",
            ),
        ),
        migrations.AlterField(
            model_name="applicationconfiguration",
            name="vector_store_database",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Vector store database",
            ),
        ),
        migrations.AlterField(
            model_name="applicationconfiguration",
            name="vector_store_host",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Vector store host",
            ),
        ),
        migrations.AlterField(
            model_name="applicationconfiguration",
            name="vector_store_password",
            field=models.CharField(
                blank=True,
                max_length=1024,
                null=True,
                verbose_name="Vector store password",
            ),
        ),
        migrations.AlterField(
            model_name="applicationconfiguration",
            name="vector_store_port",
            field=models.PositiveIntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Vector store port",
            ),
        ),
        migrations.AlterField(
            model_name="applicationconfiguration",
            name="vector_store_user",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Vector store user",
            ),
        ),
    ]
