# Generated by Django 5.2.9 on 2026-01-18 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0005_aireviewqueue"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AISuggestionHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "applied_suggestions",
                    models.JSONField(
                        help_text="JSON structure containing the AI suggestions that were applied to the document",
                        verbose_name="applied suggestions",
                    ),
                ),
                (
                    "confidence_scores",
                    models.JSONField(
                        help_text="JSON structure containing confidence scores for each applied suggestion",
                        verbose_name="confidence scores",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="applied at"),
                ),
                (
                    "rolled_back",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this suggestion has been rolled back",
                        verbose_name="rolled back",
                    ),
                ),
                (
                    "rolled_back_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="rolled back at",
                    ),
                ),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applied_ai_suggestions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="applied by",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_suggestion_histories",
                        to="documents.document",
                        verbose_name="document",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
                (
                    "rolled_back_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rolled_back_ai_suggestions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="rolled back by",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI suggestion history",
                "verbose_name_plural": "AI suggestion histories",
                "ordering": ("-applied_at",),
            },
        ),
    ]
