# Generated by Django 5.2.10 on 2026-01-26 00:15

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0007_alter_document_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aisuggestionhistory",
            name="confidence_scores",
            field=models.JSONField(
                blank=True,
                help_text="JSON structure containing confidence scores for each applied suggestion",
                null=True,
                verbose_name="confidence scores",
            ),
        ),
    ]
