# Generated by Django 5.2.10 on 2026-02-04 22:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0008_alter_aisuggestionhistory_confidence_scores"),
        ("documents", "0008_sharelinkbundle"),
    ]

    operations = []
