# Generated by Django 5.2.11 on 2026-02-05 17:39

import django.db.models.functions.text
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0009_workflowaction_passwords_alter_workflowaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowaction",
            name="assign_ocr_engine",
            field=models.CharField(
                blank=True,
                help_text="Override the OCR engine for this document. Available engines: tesseract, docling, ollama (if installed).",
                max_length=32,
                null=True,
                verbose_name="assign OCR engine",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="content_length",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.text.Length("content"),
                help_text="Length of the content field in characters. Automatically maintained by the database for faster statistics computation.",
                output_field=models.PositiveIntegerField(default=0),
                serialize=False,
            ),
        ),
    ]
