# Generated by Django 5.2.11 on 2026-02-08 17:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0009_workflowaction_passwords_alter_workflowaction_type"),
        ("documents", "0010_alter_document_content_length"),
    ]

    operations = []
