# Generated by Django 5.2.11 on 2026-02-08 10:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0009_merge_20260204_2214"),
        ("documents", "0010_alter_document_content_length"),
    ]

    operations = []
