# Generated by Django 5.2.9 on 2026-01-19 21:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1078_add_ai_suggestion_history"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ("-created",),
                "permissions": [
                    ("apply_ai_enhancement", "Can apply AI enhancement suggestions"),
                ],
                "verbose_name": "document",
                "verbose_name_plural": "documents",
            },
        ),
    ]
